_target_: src.models.poke_module.PokeWGanModule

optimizer_gen:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0004
  weight_decay: 0.0

optimizer_disc:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0004
  weight_decay: 0.0

gen:
  _target_: src.models.components.generators.DCGen
  z_dim: 100
  channels_img: 3

disc:
  _target_: src.models.components.discriminators.WDCDisc
  channels_img: 3

criterion:
  _target_: src.custom_criterions.NegativeMeanLoss

# compile model for faster training with pytorch 2.0
compile: false
