wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1695473876.587678
    t:
      1:
        - 55
        - 105
      2:
        - 55
        - 105
      3:
        - 14
        - 23
        - 37
      4: 3.10.12
      5: 0.15.10
      8:
        - 1
        - 3
        - 5
